### ISSUE TITLE
Circular references causes StackOverflowError

### ISSUE THREAD

**Issue by mgrzechocinski** [johncarl81/parceler#66] opened 2015-01-08 23:54 UTC
Hey,

this possible issue is undoubtedly inherited from the Parcelable mechanism in Android but I'm wondering if there is anything that can be done to have a quite nice strategy for handling following situation.

### The problem
Suppose we have two following pojos: `Owner` with a list of `Account`. Generally, it's a typical one to many relation to be mapped that way when using OrmLite on Android:

[Owner.java](https://github.com/mgrzechocinski/parceler-example/blob/master/app/src/main/java/net/grzechocinski/android/parceler_example/Owner.java)
```java
@Parcel
public class Owner {

    String name;

    List<Account> accounts;

    // getters,setters
```

[Account.java](https://github.com/mgrzechocinski/parceler-example/blob/master/app/src/main/java/net/grzechocinski/android/parceler_example/Account.java)
```java
@Parcel
public class Account {

    String number;

    Owner owner;

   // getters,setters
}
```

Now, trying to parcel it:
```java
Owner owner = new Owner();
owner.setName("John Brown");

Account account1 = new Account();
account1.setNumber("1234567890");
account1.setOwner(owner);

owner.setAccounts(Arrays.asList(account1));

Intent intent = new Intent(this, SecondActivity.class);
intent.putExtra(SecondActivity.OWNER_INTENT_KEY, Parcels.wrap(owner));

startActivity(intent);
```

causes StackOverflowError:
```
01-08 22:55:58.243    2159-2159/net.grzechocinski.android.parceler_example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: net.grzechocinski.android.parceler_example, PID: 2159
    java.lang.StackOverflowError
            at android.os.Parcel.writeInt(Parcel.java:484)
            at net.grzechocinski.android.parceler_example.Owner$$Parcelable.writenet_grzechocinski_android_parceler_example_Account(Owner$$Parcelable.java:105)
            at net.grzechocinski.android.parceler_example.Owner$$Parcelable.writenet_grzechocinski_android_parceler_example_Owner(Owner$$Parcelable.java:122)
            at net.grzechocinski.android.parceler_example.Owner$$Parcelable.writenet_grzechocinski_android_parceler_example_Account(Owner$$Parcelable.java:106)
            at net.grzechocinski.android.parceler_example.Owner$$Parcelable.writenet_grzechocinski_android_parceler_example_Owner(Owner$$Parcelable.java:122)
```

### Why it happens
Basically, the problem is in circular reference between `Owner` and `Account`. For those who don't get it: Parceler tries to parcel `Owner`, then it reaches `List` of `Account` so it iterates over it, trying to parcel every `Account`. While parceling particular `Account` it tries to parcel already processed `Owner` (the field in Account object). Recurrency leads us to StackOverflowError.

### Possible workarounds
Although I haven't found any workarounds to be used with Parceler, there are several SO questions about circular reference problem when parceling object manually like [this one](http://stackoverflow.com/questions/20159632/circular-reference-of-parcelable-objects) or [this one](http://stackoverflow.com/questions/18176832/android-parcelable-referencing-another-parcelable-circular-dependence).

### Why converter doesn't work
I wanted to follow the idea of having a set of parent references (`Owners` in this particular example) and setting `account.owner` reference manually by fetching it from previously filled set. To do that I implemented custom `ParcelConverter`. AFAIK, this it the official way to perform parceling of the particular type on my own. I implemented it in that way:
```java
public class AccountConverter implements ParcelConverter<Account> {

    Map<Long, Owner> parents = new HashMap<>();

    @Override
    public void toParcel(Account input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
        //unique key is some kind o indentifier, e.g. database id
        parents.put(input.getUniqueKey(), input.getOwner()); 
    }

    @Override
    public Account fromParcel(Parcel parcel) {
        Account account = Parcels.unwrap(parcel.readParcelable(getClass().getClassLoader()));
        account.setOwner(parents.get(account.getUniqueKey()));
        return account;
    }
}
```

So far, so good. I thought it should be working quite well. I registered this converter:
```java
@Parcel(converter = AccountConverter.class)
public class Account {
```
and also marked `account.owner` field as transient, so Parceler should leave handling this field to me
```java
@Transient
Owner owner;
```

Unfortunately, StackOverflowError still happens but it's different:
```
  java.lang.StackOverflowError
            at java.util.HashMap.<init>(HashMap.java:125)
            at net.grzechocinski.android.parceler_example.AccountConverter.<init>(AccountConverter.java:11)
            at net.grzechocinski.android.parceler_example.Account$$Parcelable.<init>(Account$$Parcelable.java:15)
            at org.parceler.Parceler$$Parcels$Account$$Parcelable$$0.buildParcelable(Parceler$$Parcels.java:35)
            at org.parceler.Parceler$$Parcels$Account$$Parcelable$$0.buildParcelable(Parceler$$Parcels.java:28)
            at org.parceler.Parcels.wrap(Parcels.java:87)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at net.grzechocinski.android.parceler_example.AccountConverter.toParcel(AccountConverter.java:15)
            at net.grzechocinski.android.parceler_example.Account$$Parcelable.writeToParcel(Account$$Parcelable.java:30)
            at android.os.Parcel.writeParcelable(Parcel.java:1285)
            at net.grzechocinski.android.parceler_example.AccountConverter.toParcel(AccountConverter.java:15)
            at net.grzechocinski.android.parceler_example.Account$$Parcelable.writeToParcel(Account$$Parcelable.java:30)
```
What I undestrand from Parceler sources, problem is here, in my converter class:
```java
@Override
public void toParcel(Account input, Parcel parcel) {
      parcel.writeParcelable(Parcels.wrap(input), 0);
      parents.put(input.getUniqueKey(), input.getOwner()) 
}
```
I can't call `writeParcelable` and passing result of `wrap` because `wrap(Article)` creates new converter which again tries to `writeParcelable` which uses `wrap()`, which creates new converter which... leads me to SOE.

Frankly, I'm stuck. Do you have any hints how to solve the problem of circular references? I have a feeling that choosing to implement custom converter is the right chois, but I don't want to implement parceling of the whole entity on my own. 

I'd rather like to let Parcel do it's job (by using `wrap` method), ignoring particular fields and then let me handle those particular fields manually. Is it possible?

Sample project to play with this issue is [here](https://github.com/mgrzechocinski/parceler-example).

**Comment by mgrzechocinski** [comment] 2015-01-09 00:27
Just found one possible workaround by introducing wrapper class for an entity with custom converter and is this class when `parcel.writeParcelable(Parcels.wrap()))`.  The only drawback I found is that I need to do deep copy of that class.

Sample code:
```java
//Override annotation from super class - we don't need converter anymore
    @org.parceler.Parcel
    public static class AccountParcelableWrapper extends Account{

        public AccountParcelableWrapper() {
        }

        //Deep copy
        public AccountParcelableWrapper(Account account) {
            this.number = account.getNumber();
            this.owner = account.getOwner();
        }
    }
```

and then my converter looks like this:
```java
@Override
    public void toParcel(Account input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(new AccountParcelableWrapper(input)), 0);
        parents.put(input.getUniqueKey(), input.getOwner());
    }

    @Override
    public Account fromParcel(Parcel parcel) {
        //no changes here since wrapper extends Account
    }
```

**Comment by johncarl81** [comment] 2015-01-09 02:37
@mgrzechocinski, excellent investigation into this issue.  This is definitely a bug which I thought was addressed in a previous commit.  It looks like collection of `@Parcels` is not handled correctly and after some digging around it looks like non-collections are also not handled correctly.  I will be looking into this deeper in the coming days and, if you're game, I'd appreciate your eyes as well.

To handle recursive elements like this:

```java
@Parcel
public class Account {
    Owner owner;
}
@Parcel
public class Owner {
    Account account;
}
```

Parceler should be writing code that looks like this (for Account only):
```java
public class Account$$Parcelable
    implements Parcelable, ParcelWrapper<org.parceler.Account>
{

    private org.parceler.Account account$$0;

    public final static Account$$Parcelable.Creator$$3 CREATOR =...

    public Account$$Parcelable(android.os.Parcel parcel$$9) {
        account$$0 = new org.parceler.Account();
        org.parceler.Owner owner$$1;
        if (parcel$$9 .readInt() == -1) {
            owner$$1 = null;
        } else {
            owner$$1 = readorg_parceler_Owner(parcel$$9);
        }
        account$$0 .owner = owner$$1;
    }

    public Account$$Parcelable(org.parceler.Account account$$1) {
        account$$0 = account$$1;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel$$10, int flags) {
        if (account$$0 .owner == null) {
            parcel$$10 .writeInt(-1);
        } else {
            parcel$$10 .writeInt(1);
            writeorg_parceler_Owner(account$$0 .owner, parcel$$10, flags);
        }
    }

    private org.parceler.Owner readorg_parceler_Owner(android.os.Parcel parcel$$11) { ... }

    private org.parceler.Account readorg_parceler_Account(android.os.Parcel parcel$$11){ ... }

    private void writeorg_parceler_Owner(org.parceler.Owner owner$$2, android.os.Parcel parcel$$12, int flags$$0) { ... }

    private void writeorg_parceler_Account(org.parceler.Owner owner$$2, android.os.Parcel parcel$$12, int flags$$0) { ... }

    @Override
    public int describeContents() {
        return  0;
    }

    @Override
    public org.parceler.Account getParcel() {
        return account$$0;
    }

    private final static class Creator$$3 implements Creator<Account$$Parcelable>{...}
}
```

^ Tons of boilerplate here, but the key is that there is a method call for each Account and Owner that can call each other if necessary.

**Comment by johncarl81** [comment] 2015-01-09 03:00
Related, I thought this case was tested: https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/CircularReferenceTest.java

**Comment by johncarl81** [comment] 2015-01-09 03:17
@mgrzechocinski, excellent investigation into this issue.  Oh, and I finally see the issue.  You need to assign ownership to one side of the relationship.  You can do this by using @Transient:

```java
@Parcel
    public static class Account {
        String number;
        @Transient
        Owner owner;
    }

    @Parcel
    public static class Owner {
        String name;
        List<Account> accounts;
    }
```
Unfortunately this means you can only `Parcel.wrap()` from one side:
```java
        Owner owner = new Owner();
        owner.setName("John Brown");

        Account account1 = new Account();
        account1.setNumber("1234567890");
        account1.setOwner(owner);

        owner.setAccounts(Arrays.asList(account1));

        Parcels.wrap(owner);
```
Yes, there may be a better way to do this.  I'd appreciate your input and eyes on this issue.

**Comment by johncarl81** [comment] 2015-01-09 03:37
One idea is to manage the circular reference (Hibernate's mappedBy comes to mind):
```java
    @Parcel
    public static class Account {
        String number;
        @ParcelProperty(mappedBy="accounts")
        Owner owner;
    }

    @Parcel
    public static class Owner {
        String name;
        List<Account> accounts;
    }
```
But this may get pretty hairy with collection support.

**Comment by johncarl81** [comment] 2015-01-15 01:28
@mgrzechocinski, is this sort of mappedBy functionality necessary for your use case?

**Comment by pablobaldez** [comment] 2015-01-20 17:31
Hello @johncarl81 ,
mappedBy functionality it's very important for my case. There are any possible to implement this one in a future Parceler release?

**Comment by johncarl81** [comment] 2015-01-20 17:41
@pablobaldez absolutely!  Would you like to try your hand at a PR?

**Comment by johncarl81** [comment] 2015-01-20 18:14
@pablobaldez, would you mind sharing some specifics of your issue?

**Comment by pablobaldez** [comment] 2015-01-20 18:34
@johncarl81 i have an one-to-many bidiretional relashionship like the sample of @mgrzechocinski  . I did an workaround like this to work:
```java
@Parcel
public class Product{
    String name;
    List<Note> notes;
    public Product() {}
}
```
```java
//the "many" side
@Parcel
public class Note{
    private static HashMap<String,Product> workaround = new HashMap<>();
    
    //name is unique
    String name;
    Product product;

    @ParcelConstructor
    public Note(String name) {
        this.name = name;

        if (workaround.containsKey(name)){
            product = workaround.get(name);
        }
    }
    
    public void setProduct(Product product) {
        workaround.put(name, product);
        this.product = product;
    }
}
```

so, first i create the "one" relashionship side and, after instantiate objects, i create the "many" side.

```java
    List<Note> notes = new ArrayList<>();
    Note note = new Note("without sugar");
    notes.add(note);
    Product product = new Product("orange juice", notes);
    note.setProduct(product);

    Parcelable wrapped = Parcels.wrap(product);
    Product wrappedProduct = Parcels.unwrap(wrapped);
```

**Comment by pablobaldez** [comment] 2015-01-20 18:38
apparently this workaround solve my problems, but i think that this solution can be many limitations...

**Comment by johncarl81** [comment] 2015-01-20 19:04
I was particularly wondering if you were using another library that had some sort of bidirecitonal relationship that was not mirrored in Parceler.  Yeah, the limitation is that the `@Transient` side of the relationship would be null after being deserialized.

**Comment by pablobaldez** [comment] 2015-01-20 21:46
No. I have tested my application and the both sides of relationship are not nulls after call unwrap. Look that "workaround " HashMap is static and when i call setProduct it's populated with an unique identifier.

My english it's a little poor, so i'm not understand what you said about "using another library". I'm not using another library.

**Comment by johncarl81** [comment] 2015-01-21 02:26
I can't say I approve of that workaround.  I'd do something like the following instead:
```java
@RunWith(RobolectricTestRunner.class)
@Config(manifest=Config.NONE)
public class AccountOwnerTest {

    //Owner handles the bidirectional relationship
    @Parcel
    public static class Account {
        @Transient
        Owner owner;
    }

    @Parcel
    public static class Owner {
        List<Account> accounts = new ArrayList<Account>();

        @ParcelProperty("accounts")
        protected void setAccounts(List<Account> accounts) {
            for (Account account : accounts) {
                account.owner = this;
            }
            this.accounts = accounts;
        }
    }

    @Test
    public void testCircularReference(){
        Owner owner = new Owner();

        Account account1 = new Account();
        account1.owner = owner;

        owner.setAccounts(Arrays.asList(account1));

        Owner unwrap = Parcels.unwrap(ParcelsTestUtil.wrap(owner));

        assertNotNull(unwrap.accounts.get(0).owner);
    }

    //Account handles the bidirectional relationship
    @Parcel
    public static class Account2 {
        Owner2 owner;

        @ParcelProperty("owner")
        protected void setOwner(Owner2 owner) {
            owner.accounts.add(this);
            this.owner = owner;
        }
    }

    @Parcel
    public static class Owner2 {
        @Transient
        List<Account2> accounts = new ArrayList<Account2>();
    }

    @Test
    public void testCircularReference2(){
        Owner2 owner = new Owner2();

        Account2 account = new Account2();
        account.setOwner(owner);

        owner.accounts = Arrays.asList(account);

        Account2 unwrap = Parcels.unwrap(ParcelsTestUtil.wrap(account));

        assertFalse(unwrap.owner.accounts.isEmpty());
    }
}
```

**Comment by pablobaldez** [comment] 2015-01-21 17:06
your approach is simpler and probably more optimized. thank you!

**Comment by pablobaldez** [comment] 2015-01-21 17:10
if i have doubts about Parcel usage like annotations and best practices where can i send it?

**Comment by johncarl81** [comment] 2015-01-21 18:27
Feel free to email me directly or post an issue here on github.

**Comment by mgrzechocinski** [comment] 2015-01-21 23:43
Hey, sorry for a delayed response. I'm absolutely interested in resolving this issue in Parceler library and then not having workarounds I posted above. 

@johncarl81 seems like your piece of code should work, but I think we all agree that's still a workaround and we need to find a way to handle circular references transparently. Do you have any plans to fix that or could I dive into the code and try to create a PR for that?

**Comment by johncarl81** [comment] 2015-01-21 23:50
@mgrzechocinski, please move forward with a PR.  I'd love some collaboration on this.

**Comment by mgrzechocinski** [comment] 2015-01-21 23:50
Fine. Would try to find few evenings for that. Thanks. M.

**Comment by johncarl81** [comment] 2015-01-23 05:55
@mgrzechocinski, I was just thinking about this.  I think this case is a subset of a larger circular reference problem.  How about the following case:
```java
class A { B b; }
class B { C c; }
class C { A a; }
```
I believe this would have a similar problem as the simple bidirectional relationship case.  We would have to analyze the entire graph of `@Parcel` beans to determine if these loops exist in order to handle them properly.  So, that begs the question, should we handle this?  I'd appreciate your thoughts.

**Comment by mgrzechocinski** [comment] 2015-01-26 23:48
Yep, you're right. Maybe we should figure out how Serializable can handle this properly?

**Comment by johncarl81** [comment] 2015-01-27 00:27
I like what Jessie Wilson says on the subject in relation to Gson: https://code.google.com/p/google-gson/issues/detail?id=137#c7  Maybe we could attempt a similar strategy.

**Comment by StErMi** [comment] 2015-10-02 15:54
Hi guys did you found a solution about this? I've this kind of issue using Ream.io because of Circular References and I would like to solve the StackOverflow crash ;)

**Comment by johncarl81** [comment] 2015-10-02 19:54
@StErMi, we have not yet implemented this, and I'm on the fence if we ever well, care to share your details or use cases?

**Comment by StErMi** [comment] 2015-10-03 07:02
Hi @johncarl81 I came along with this problem while using Realm.io for Android.
The issue I've created on the Realm.io repo is here: https://github.com/realm/realm-java/issues/1522

PLCategory.java

```java
@Parcel(implementations = { PLCategoryRealmProxy.class }, value = Parcel.Serialization.BEAN, analyze = { PLCategory.class })
public class PLCategory extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("items")
    @Transient
    private RealmList<PLItem> items;

    //constructor, getters and setters

}
```

PLItem.java

```java
@Parcel(implementations = { PLItemRealmProxy.class }, value = Parcel.Serialization.BEAN, analyze = { PLItem.class })
public class PLItem extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("category")
    private PLCategory category;

    //constructor, getters and setters

}
```

When I fetch a Category from the database with Realm.io it has a reference (lazy) to many items. So every item has a reference to the category that has a reference to items and so. This is the circular reference. 

This is not a problem with Realm because this reference is lazy so it will be loaded only when I try to access it. 
The problem is when I do 

```java
Parcels.wrap(category);
```

From the Realm.io documentation about Parceler (https://realm.io/docs/java/latest/#parceler)

```
Once an object has been been parcelled, it becomes detached from Realm and at this point behaves like a standalone object containing a snapshot of the data. Further changes to this object will not be persisted in Realm
```

This means that when I do ```Parcels.wrap(category);``` it will load all the lazy reference and will actually create the circular references crash.

I think that solutions can be 2:

1) They solve the issue from the Realm.io side letting me select which fields really load from the database (but I thin think that this will be not an option)
2) Parceler let me specify the level of recursion I want to get at maximum when I wrap the object.

Is it possible to do it? Do you have at least a good workaround for my issue?

**Comment by heitorpr** [comment] 2016-01-20 11:56
Guys any possible change on this issue? Im having it too, the same as @mgrzechocinski, for now I will use @Transient notation, but I hope we have a solution on this =).

Obs.: I'm using Realm, so I needed to put @Transient on getProperty().

**Comment by johncarl81** [comment] 2016-01-20 16:36
This is going to require quite a bit of refactoring to accomplish.  `@Transient` is a fine technique to break the circular references, at least for the time being.

**Comment by johncarl81** [comment] 2016-02-06 18:10
I think I have a reasonable solution here:  #154.  Would love feedback before merging and releasing.

**Closed** 2016-02-27 16:01 UTC

**Comment by anantrao07** [comment] 2019-06-28 14:10
I was trying Redux and i had to implement serialization/PArcelable on the parent fragment itslef. 
Which is nothing but just a fragment reference . So my question is can i parcelize the fragment  reference ? 
As of now am getting Stack over flow error  in WriteToPArcel  
{
dest.writeParcel(this, 0)
}

**Comment by johncarl81** [comment] 2019-06-28 21:04
Not sure why you would want to do this... could you provide a working example of your problem @anantrao07?
